name: update-chnroute-gfwlist

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */12 * * *'
jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          make
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.TOKEN }}
